# Generated by Django 2.0.5 on 2018-08-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiautotest', '0004_httprunresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpapi',
            name='assertType',
            field=models.CharField(choices=[('noselect', '没有'), ('in', '包含'), ('status_code', '状态码')], default='noselect', max_length=20, verbose_name='断言类型'),
        ),
    ]
