# Generated by Django 2.0.5 on 2018-09-03 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiautotest', '0005_auto_20180827_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='接口测试名称')),
                ('httpapis', models.CharField(max_length=50, verbose_name='包含http接口id')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiautotest.Project', verbose_name='所属项目')),
            ],
        ),
        migrations.CreateModel(
            name='HttpTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('httprunresults', models.CharField(max_length=50, verbose_name='运行结果id')),
                ('status', models.CharField(max_length=50, verbose_name='测试结果')),
                ('httptest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiautotest.HttpTest', verbose_name='测试')),
            ],
        ),
        migrations.AlterField(
            model_name='httpapi',
            name='assertType',
            field=models.CharField(choices=[('noselect', '无'), ('in', '包含'), ('status_code', '状态码')], default='noselect', max_length=20, verbose_name='断言类型'),
        ),
    ]
